// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// computeErrorMatrix
NumericMatrix computeErrorMatrix(NumericMatrix Zrand, NumericMatrix Erand, NumericVector Yrand, NumericMatrix Hrand, NumericMatrix Q, NumericVector lambda, int K);
RcppExport SEXP _KPR_computeErrorMatrix(SEXP ZrandSEXP, SEXP ErandSEXP, SEXP YrandSEXP, SEXP HrandSEXP, SEXP QSEXP, SEXP lambdaSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Zrand(ZrandSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Erand(ErandSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Yrand(YrandSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Hrand(HrandSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Q(QSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(computeErrorMatrix(Zrand, Erand, Yrand, Hrand, Q, lambda, K));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_KPR_computeErrorMatrix", (DL_FUNC) &_KPR_computeErrorMatrix, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_KPR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
