# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeErrorMatrixCpp <- function(Zrand, Erand, Yrand, Hrand, Q, lambda, K, cov_missing) {
    .Call(`_KPR_computeErrorMatrixCpp`, Zrand, Erand, Yrand, Hrand, Q, lambda, K, cov_missing)
}

